### ISSUE TITLE
Добавления PSR логов 

### ISSUE THREAD

**Issue by shokhaa** [yoomoney/yookassa-payout-sdk-php#13]
Добрый день вы не смогли бы принять этот pull request 
https://github.com/yoomoney/yookassa-payout-sdk-php/pull/12

**Comment by ostulov** [comment]
Добрый день!

Благодарю за обращение, рассмотрим Ваше предложение

**Comment by shokhaa** [comment]
@ostulov Долго будете рассмотреть?

**Comment by ostulov** [comment]
Сделали обновление v2.2.4
