### ISSUE TITLE
Проведение выплат самозанятым

### ISSUE THREAD

**Issue by shokhaa** [yoomoney/yookassa-payout-sdk-php#17]
Не было сеттеров и геттеров по доку 

https://yookassa.ru/docs/payouts/supplementary/self-employed/make-payout#api-request

создал 2 pull request пожалуйста проверите и принимайте! 

https://github.com/yoomoney/yookassa-payout-sdk-php/pull/16
https://github.com/yoomoney/yookassa-payout-sdk-php/pull/15

**Comment by ostulov** [comment]
Добрый день!

Благодарю, рассмотрим Ваши предложения!

**Comment by shokhaa** [comment]
@ostulov примерно сколько время займет это?

**Comment by ostulov** [comment]
До конца этой недели сделаем обновление

**Comment by ostulov** [comment]
Добавили в версии v2.2.5
